### ISSUE TITLE
No bar chart in frequency distribution

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#114] opened 2017-09-22 11:39 UTC
https://wiki.korpus.cz/doku.php/kurz:vyhodnoceni_dotazu#frekvencni_distribuce_slovnich_tvaru namely https://wiki.korpus.cz/lib/exe/detail.php/kurz:lemma_slovni_tvary_bezvelkych.png?id=kurz%3Avyhodnoceni_dotazu is the chart a new addition or is there something broken?

**Comment by vidiecan** [comment] 2018-04-23 11:52
closing, cannot reproduce in the latest version (I see the bars)

**Closed by vidiecan** 2018-04-23 11:52 UTC
