### ISSUE TITLE
Endless wait for Display options

### ISSUE THREAD

**Issue by TomazErjavec** [ufal/lindat-kontext#148] opened 2017-11-17 22:27 UTC
Clicking on "Display options" on the Concordance window as an anon user results in a endless wait.
This option should be rather disabled (grayed out, as menu items) for anon users, as you probably can't verify their identity. Alternativelly, you can have it enabled, which is the same as noSketch Engine: there anon can change the prefernces, but they are then inherited by the next user. Either option has its (dis)advantages.

It is a small bug, but the user gets the impression that, well, it is a bug...

**Comment by kosarko** [comment] 2017-11-18 15:01
this is duplicate of #82, there's a PR pending. Should be fixed with the "next release"

**Closed by kosarko** 2017-11-18 15:01 UTC
