### ISSUE TITLE
FCS: unsupported index in Aggregator

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-kontext#24] opened 2016-06-10 10:21 UTC
Lindat corpora have several issues within FCS aggregator (http://weblicht.sfs.uni-tuebingen.de/Aggregator/):
- aggregator returns _unsupported index_ error for all spoken corpora, facebook
  sentiment corpus, Urdu corpus etc. 
- it displays entries with empty result in case the searched word is not found in the corpus
- for some corpora and some queries (e.g. Finnish-ftb, "a") it returns _general system error_

Screenshot:

![unsupported index](https://cloud.githubusercontent.com/assets/2538188/15961534/856b825c-2f05-11e6-99a0-60eba09bf130.png)
![general_system_error](https://cloud.githubusercontent.com/assets/2538188/15961537/8b0923f4-2f05-11e6-9a32-cd768e81faea.png)
![unsopported](https://cloud.githubusercontent.com/assets/2538188/15961539/8d307024-2f05-11e6-95ca-328fa71333fc.png)

**Comment by vidiecan** [comment] 2017-09-12 11:49
duplicate of #33

**Closed by vidiecan** 2017-09-12 11:49 UTC
